text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
deploy:
  default:
    dst: "server:file_system_location"
    options: [ '-gpPrvz' ]
base_url: "http://www.bioinformaticszen.com"
title: "Bioinformatics Zen"
subtitle: "Michael Barton's Bioinformatics and Research Notes"
author_uri: "http://www.bioinformaticszen.com"
author_name: "Michael Barton"
author_email: "mail@bioinformaticszen.com"
analytics_token: "UA-1362555-1"
navigation:
rights: "Creative Commons Attribution 3.0 Unported"
