text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
deploy:
  default:
    dst: "webserver:/home/admin/sites/bioinformaticszen.com"
    options: [ '-gpPrvz' ]
base_url: "http://bioinformaticszen.com"
site:
  title: "Bioinformatics Zen"
  subtitle: "Michael Barton's Bioinformatics and Research Notes"
  url: "http://bioinformaticszen.com"
  favicon: false
  analytics_token: "UA-1362555-1"
  feed: 'http://feeds.feedburner.com/BioinformaticsZen'
  rights: "Creative Commons Attribution 3.0 Unported"
  navigation:
    index: '/'
    feed: 'http://feeds.feedburner.com/BioinformaticsZen'
    contact: 'mailto:mail@bioinformaticszen.com'
    twitter: 'http://twitter.com/bioinformatics'
    youtube: 'http://www.youtube.com/user/bioinformaticszen'
feed: 'http://feeds.feedburner.com/BioinformaticsZen'
author:
  uri: "http://www.michaelbarton.me.uk"
  name: "Michael Barton"
  email: "mail@michaelbarton.me.uk"
scripts:
  - "https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
  - "/fancybox/javascript.js"
  - "/javascript/prettify.js"
stylesheets:
  "/stylesheets/stylesheet.css": "screen,projection"
  "/fancybox/styles.css": "screen,projection"
