text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
deploy:
  default:
    dst: "server:file_system_location"
    options: [ '-gpPrvz' ]
site:
  title: "Bioinformatics Zen"
  url: "http://www.bioinformaticszen.com"
  analytics_token: "UA-1362555-1"
author:
  url: "http://www.michaelbarton.me.uk
