text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
deploy:
  default:
    dst: "webserver:/home/admin/sites/bioinformaticszen.com"
    options: [ '-gpPrvz' ]
base_url: "http://bioinformaticszen.com"
title: "Bioinformatics Zen"
subtitle: "Michael Barton's Bioinformatics and Research Notes"
author_uri: "http://bioinformaticszen.com"
author_name: "Michael Barton"
author_email: "mail@bioinformaticszen.com"
analytics_token: "UA-1362555-1"
rights: "Creative Commons Attribution 3.0 Unported"
navigation:
  feed: 'http://feeds.feedburner.com/BioinformaticsZen'
  email: 'mailto:mail@bioinformaticszen.com'
  twitter: 'http://twitter.com/bioinformatics'
  videos: 'http://www.youtube.com/user/bioinformaticszen'
feed: 'http://feeds.feedburner.com/BioinformaticsZen'
